### PR TITLE
Repo readme

### PR DESCRIPTION
**Pull request by clusty**
First iteration on repo documentation.

### CODE REVIEW

**Review by clusty — COMMENTED** [review]
I'm liking it :)

**Comment by sebastienduverne** [comment]
I've put some more glue between the three .md files available in the repo's root to make the whole a bit more uniform, visible and part of the same user experience. However, I suppose we could have all on the same page. Opinions?

**Comment by clusty** [comment]
> I've put some more glue between the three .md files available in the repo's root to make the whole a bit more uniform, visible and part of the same user experience. However, I suppose we could have all on the same page. Opinions?

I am a bit more reluctant to do that cause it might mess with the repo legal structure.

**Review by mfe — APPROVED** [review]
LGTM !
Feels as good as a spring cleaning ! :D

**Review by cguer — APPROVED** [review]
QA approved 👍!

**Pull request merged**
